### ISSUE TITLE
Disable compilation flag

### ISSUE THREAD

**Issue by NicoMuleo** [snitch-org/snitch#186]
It would be useful to have a compilation flags that allows to completely deactivate/delete every Snitch functionality at compilation time.

> Something similar to [doctest DOCTEST_CONFIG_DISABLE](https://github.com/doctest/doctest/blob/master/doc/markdown/configuration.md#doctest_config_disable)

**Comment by cschreib** [comment]
Sounds useful indeed.

**Comment by NicoMuleo** [comment]
Great, I see you added in the milestone, thank you!!
Do you have a general idea of when this might feature be implemented?

**Comment by cschreib** [comment]
Nothing precise, no. I don't think it's a particularly difficult thing to implement, although the devil might be in the details (e.g., how to test this, what should be compiled-out vs what has to stay, etc.).

If you're keen to have this available sooner rather than later, you're welcome to create a pull request (see [contribution guidelines](https://github.com/snitch-org/snitch/blob/main/CONTRIBUTING.md#contributing-a-change)). Otherwise, someone else will need to pick this up when they have a bit of free time, which is the bit that is difficult to predict ;)

**Comment by NicoMuleo** [comment]
Here is the [pull request](https://github.com/snitch-org/snitch/pull/192).

**Comment by cschreib** [comment]
Thank you for the contribution!
